import Head from 'next/head'
import Form from '@rjsf/material-ui';

export async function getServerSideProps(context) {
  const schema = await fetch('http://localhost:3000/api/schema');
  return {
    props: {
      schema: await schema.json(),
    }
  }
}

export default function Home({ schema }) {
  const onSubmit = async ({ formData }) => {
    await fetch('/api/config', {
      method: 'POST',
      body: JSON.stringify(formData)
    });
  }
  const onError = (err) => {
    console.error(err);
  }

  return (
    <div>
      <Head>
        <title>Virtual Device Editor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Form
        schema={schema}
        onSubmit={onSubmit}
        onError={onError}
      />
    </div>
  )
}
